#!/usr/bin/env python3
"""Render Crew's formula from checksums of immutable release archives."""
import argparse
import pathlib
import re

TARGETS = ("darwin_arm64", "darwin_amd64", "linux_arm64", "linux_amd64")


def render(version, checksums):
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version):
        raise ValueError("version must be a stable semantic version, e.g. 0.1.0")
    for target in TARGETS:
        if not re.fullmatch(r"[0-9a-f]{64}", checksums.get(target, "")):
            raise ValueError(f"missing or invalid SHA-256 for {target}")
    base = f"https://github.com/tesserix/tesserix-crew/releases/download/v{version}"
    lines = [
        "# Generated by scripts/render_formula.py; do not edit checksums manually.",
        "class Crew < Formula",
        '  desc "One persistent coding session across your subscribed coding agents"',
        '  homepage "https://github.com/tesserix/tesserix-crew"',
        f'  version "{version}"',
        '  license "Apache-2.0"',
        "",
    ]
    for os_name, stanza in (("darwin", "macos"), ("linux", "linux")):
        lines += [f"  on_{stanza} do"]
        for arch, condition in (("arm64", "arm"), ("amd64", "intel")):
            target = f"{os_name}_{arch}"
            lines += [
                f"    on_{condition} do",
                f'      url "{base}/crew_{version}_{target}.tar.gz"',
                f'      sha256 "{checksums[target]}"',
                "    end",
            ]
            if arch == "arm64":
                lines += [""]
        lines += ["  end", ""]
    lines += [
        "  def install",
        '    bin.install "crew"',
        "  end",
        "",
        "  test do",
        '    assert_equal "crew #{version}\\n", shell_output("#{bin}/crew version")',
        "  end",
        "end",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--assets", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    import hashlib
    checksums = {
        target: hashlib.sha256(
            (args.assets / f"crew_{args.version}_{target}.tar.gz").read_bytes()
        ).hexdigest()
        for target in TARGETS
    }
    formula = render(args.version, checksums)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(formula)


if __name__ == "__main__":
    main()
